[package]
name = "md2scrap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

pulldown-cmark = "0.9.2"
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.1.4", features = ["derive"] }
